@startuml
skinparam arrowThickness 1.1
skinparam classBackgroundColor LOGIC_COLOR
skinparam classAttributeIconSize 0

class AssignmentMap {
-assignments: ObservableMap<AssignmentName, Assignment>
+setAssignmentMap(): void
+createUpdatedMap(): AssignmentMap
+contains(): boolean
+get(): Assignment
}

class Assignment {
-assignmentName: AssignmentName
-grade: Grade
-comment: Comment
+getName(): AssignmentName
+getGrade(): Grade
+maxGrade(): String
+gradingStatus(): boolean
+getComment(): Comment
+commentStatus(): boolean
+copyAssignment(): Assignment
}

class AssignmentName {
-assignmentName: String
+toString(): String
}

class Grade {
-actualGrade: String
-maxGrade: String
-isGraded: boolean
+getMax(): String
+getIsGraded(): boolean
+ungrade(): Grade
}

class Comment {
-commentBody: String
-isCommented: boolean
+getIsCommented(): boolean
+toString(): String
}

AssignmentMap o-- "*" Assignment: assignment
Assignment o-- "1" AssignmentName: assignmentName
Assignment o-- "1" Grade: grade
Assignment o-- "1" Comment: comment
@enduml
