@startuml
skinparam arrowThickness 1.1
skinparam classBackgroundColor LOGIC_COLOR
skinparam classAttributeIconSize 0

class Assignment {
-comment: Comment
+getComment(): Comment
+commentStatus(): boolean
}

class Comment {
-commentBody: String
-isCommented: boolean
+getIsCommented(): boolean
+toString(): String
}

Assignment o-- "1" Comment: comment
@enduml
