@startuml
hide circle
skinparam classAttributeIconSize 0

Class Consultation {
    -date: LocalDate
    -time: LocalTime
    +getDate(): LocalDate
    +getTime(): LocalTime
    +getStudentsNames(): Set<Name>
    +getStudents(): Set<Person>
    +isSameConsultation(): boolean
}

Class Person {
    -name: Name
}

Consultation o-- "1...*" Person : students
@enduml
