@startuml
skinparam arrowThickness 1.1
skinparam classBackgroundColor LOGIC_COLOR

Assignment o-- Grade

class Assignment {
grade: Grade
getGrade(): Grade
maxGrade(): String
gradingStatus(): boolean
}

class Grade {
actualGrade: String
maxGrade: String
isGraded: boolean
getMax(): String
getIsGraded(): boolean
ungrade(): Grade
}


@enduml