@startuml
skinparam arrowThickness 1.1
skinparam classBackgroundColor LOGIC_COLOR
skinparam classAttributeIconSize 0

class Assignment {
-grade: Grade
+getGrade(): Grade
+maxGrade(): String
+gradingStatus(): boolean
}

class Grade {
-actualGrade: String
-maxGrade: String
-isGraded: boolean
+getMax(): String
+getIsGraded(): boolean
+ungrade(): Grade
}

Assignment o-- "1" Grade: grade
@enduml
