@startuml
!include style.puml

mainframe **sd** execute UpdateTaskProgressCommand

participant "x:UpdateTaskProgressCommand" as UpdateTaskProgressCommand LOGIC_COLOR

participant ":Model" as Model MODEL_COLOR

participant ":TaskListBook" as TaskListBook MODEL_COLOR_T2

participant ":TaskList" as TaskList MODEL_COLOR_T3


[-> UpdateTaskProgressCommand : execute()
activate UpdateTaskProgressCommand

UpdateTaskProgressCommand -> UpdateTaskProgressCommand : createTask(taskToEdit, descriptor)
activate UpdateTaskProgressCommand

UpdateTaskProgressCommand ---> UpdateTaskProgressCommand
deactivate UpdateTaskProgressCommand

UpdateTaskProgressCommand -> Model : setTask(taskToEdit, editedTask)
activate Model

Model -> TaskListBook : setTask(taskToEdit, editedTask)
activate TaskListBook

TaskListBook -> TaskList : editTask(taskToEdit, editedTask)
activate TaskList

TaskList ---> TaskListBook
deactivate TaskList

TaskListBook ---> Model
deactivate TaskListBook

Model --> UpdateTaskProgressCommand

UpdateTaskProgressCommand --> Model : updateFilteredTaskList()

Model ---> UpdateTaskProgressCommand
deactivate Model

[<-- UpdateTaskProgressCommand
deactivate UpdateTaskProgressCommand

@enduml
